# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField()),
                ('summary', models.CharField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('link', models.URLField(max_length=500)),
                ('img', models.URLField(max_length=500)),
                ('book_type', models.CharField(choices=[('Novel', 'nov'), ('Hardcover', 'hc'), ('Paperback', 'pb'), ('Kindle', 'knd'), ('Audible', 'aud'), ('Magazine', 'mag')], max_length=100)),
                ('writers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookrest.Author')),
            ],
        ),
    ]
