# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookrest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='writers',
        ),
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
