# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookrest', '0002_auto_20160805_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='pub_date',
            field=models.DateField(),
        ),
    ]
